font=JetBrainsMono Nerd Font:style=Regular:size=12
font-bold=JetBrainsMono Nerd Font:style=Bold:size=12
font-italic=JetBrainsMono Nerd Font:style=Italic:size=12
font-bold-italic=JetBrainsMono Nerd Font:style=Bold Italic:size=12

# initial-window-size-pixels=800x600
pad=20x20

[environment]

[bell]

[scrollback]

[url]

[cursor]
style=beam
blink=yes

[mouse]

[touch]

[colors]
alpha=0.9
foreground=cdd6f4
background=1e1e2e

regular0=11111b  # black
regular1=f38ba8  # red
regular2=a6e3a1  # green
regular3=f9e2af  # yellow
regular4=89b4fa  # blue
regular5=a6e3a1  # magenta
regular6=94e2d5  # cyan
regular7=cdd6f4  # white

bright0=4c4c4c  # bright black
bright1=c49ea0  # bright red
bright2=9ec49f  # bright green
bright3=ceb188  # bright yellow
bright4=a39ec4  # bright blue
bright5=c49ec4  # bright magenta
bright6=9ec3c4  # bright cyan
bright7=f5f5f5  # bright white

[csd]

[key-bindings]
show-urls-launch=Control+Shift+u
unicode-input=Control+Shift+o

[search-bindings]

[url-bindings]

[text-bindings]

[mouse-bindings]
